var buttons = document.querySelectorAll("button");
var modal = document.getElementById("myModal");
var synopsis = document.getElementById("synopsis");
var closeBtn = document.getElementsByClassName("close")[0];
var toggle = document.getElementById('language-toggle');
var language = document.getElementById('language');
var title = document.querySelector('.title');

var lang = {
  "English": {
    "selection": "SELECT YOUR SERIE/FILM<br>IN THE ",
    "presentation": "The film / serie is :",
    "Revenge of Math": "After receiving death threats from his former rival and destroying everything he has. The only weapon our hero will use for revenge is math, which gives him impressive physical and mental strength.",
    "Math Hard": "During a party, the Nakatomi Plaza is attacked by three terrorists named Math, Emma and Tic, and they are by the way geniouses of mathematics. They will hide three bombs in the building. To disarm the first one, you have to solve Poincaré's conjecture. For the second one, you have to decipher a code. And for the last one, you have to break a program. However, the only person that can save everybody, named John MathClain, doesn't know anything about maths, as he enjoys Philosophy, Arts and History. Will he be able to save all the hostages ?",
    "Breaking Maths": "This is a story about a math teacher who found a way to make good money but he doesn’t know that this life will change his life forever...",
    "Father's Plan": "So Father's plan is a movie where a teen boy wants to be a professional fighter but he's very bad at maths, his father will told him to improve his maths skills because it will help him in mma. During the movie, the teen's gonna understand his father's advice.",
    "New Life": "Bryan is a man who has lived in poverty since childhood with parents who had little income, however he is a man who loves mathematics, his talent will allow him to participate and win a competition that contains a large sum of money in addition to obtaining a stable job to work in scientific research. After the victory of his life Bryan shares this money with his family.",
    "Mathematician's World": "After being bully 2 years Albert Mathstein decide to end his life, but God gives him a second chance in another world...",
    "The Luckiest": "After meeting the professor Brown, Martin a young man in debt decided to create a twisted theory with him to earn a lot of money and be able to pay off his loan. But the gang leader el sombrero, his lender tries to find out his theory and steal his money. Will Martin be able to hide his theory and keep his money ?",
    "JumanPI": "It's the story of four teenagers called Jake, Swan, Clara and Mike, who are imprisoned in a video game called JUMANPI. to get out, they must pass mathematical and physical tests. The tests will be hard and dangerous.",
    "Koh Sinus": "In this show of seven episodes, we follow the story of seven people lost on an island. To leave the island, they must solve maths mysteries and try to survive. Each episode is seen with the point of view of a character. This show, as intriging as funny, is made for laugh and relax. Each caracter has a different personality, which make this show funny and original. Good viewing...",
    "Mathman": "A math teacher who get stung by a compass gets superpowers which give him abilities, like throw math tools. He will meet some opponents like Histoman who can create a giant world globe. Histoman is the most hated antagonist. His allies are ELS and Physics teacher.",
    "The World of Math": "This is the story of a young boy who starts a trip to find his mother during his birthday...",
    "Find by the Maths": "The story begins in New-York city in a rich neighbourhood named Upper East Side. The two main characters are Stondy and Michael. Both are in a private school very expansive and if Michael is here it's due to a scholarship in mathematics. WHil Stondy is rich, Michael, unlike the other students, lives in a classic neighbourhood in Brooklynn. He lives with his parents and his brothers. As his schoolmates don't accept his difference, Michael is quite alone. To change that, he decides to design a trick to get all the answers of all the exams. He will start to get appreciate by his schoolmates, but soon problems will appear...",
    "Disappearance": "In order to find their friend and other missing person, five childhood friends must make a mathematical equation with which they can reconstruct a map, on which will appear the position of the missing persons. Eliotte, benjamin, Clarisse, Lana, Ella go on an adventure to find their friend and the missing people for that they will have to be endowed with intelligence to solve the equations that await them",
    "Stranger Maths": "A math teacher want to have super power . So he use a artefact calculator in the calss .hé have super power and the student ! But the power off student is very noob .For exemple in the second episode a guys if hé spawn a group of frog in the first number is a Bad event. The third is a another guy can transform in fly if he see a fractal so he want creat a WW3 .On the episode 4 a girl Can creat math tool so mant firm want to kidnap him . After a girl Can change a probability so she wants to give Monnet for homeless. At the end it have a battle between student and teacher. Students win, but the teacher is not really dead...<br><br><br><u>I am not responsible for the mistakes.<u>",
    "Shrek (revisited version)": "So for this movie of Shrek, it will be the same story as the original movie but with somethings new like jokes and we aren’t going to do the fourth movies of the saga. We are only doing the first movie because we don’t have enough time to do the fourth movies.",
    "Ridiculous Maths": "Make satire of french politics doing math debates.",
    "My friend this genius": "Steve, an FBI secret agent has been looking for the biggest drug dealers in Texas for several months. To do this, he must solve real puzzles each time to find the slightest track. One day, he defends Tobias, a 15-year-old boy who turns out to be a math whiz and enigma, harassed by boys in his neighborhood. But, inadvertently, Steve drops his taser and Tobias goes looking for it to return it and thank him. But, he discovers his base as well as his secrets. Tobias offers Steve his help. At the beginning, this one refuses and wants to erase the memory, but accepts because he is desperate. It was the start of a long friendship...",
    "Maleficient calculators": "The story happens in 2069.Calculators have almost conquers the world. The protagonist is texas,a boy from...well, Texas. With a group of scientist, he will try to stop the calculators boss,Géant Casio, by resolving his equation to kill him. But there is aprice: the one that discovers the solution and tell it to G.C has to die with him. Will Texas find the equation and accept to die to save the world ?",
    "Hope to see you again...": "During the Second World War, Emile Moreau, a young jewish math Ph.D met a little abandoned girl named Valentina. They lived in a storyless town with any problem. He decided to welcome her in his house and teach her everything he knows in math stuff. One day, at work, the War alarm sounds everywhere in the town. Emile ran to his house but he found nobody. As a jewish people he is brought away in a camp. Would Emile survive ? Where is Valentina ? Will they meet each other again ?",
    "The Mental Calculus": "The lady decides to face in a mathematical duel all the men of her city, she will encounter several dificulties but she will never strain her arms, to prove that women are not inferior and that they can even be more intelligent. Poly Gon will succeed in her objective and change the minds.",
    "Strategic War": "In a world of magic, peace may be hard to obtain. In this world, all the Kingdoms are starting a war against each other. For the Kingdom of Flos Viridis, only one hope remains, Koji, a mathematicien, who currently works as an orthoprothesist and is the best strategist of this kingdom. However, he refuses, but when the king asks his best friend, Myla, a renowned soldier, to be part of the royal guard, he accepts. Now living in the castle, to help the king, he notices that the prince, the son of the king, may have never set foot outside the castle and he is not the only one as a younger, unknown to the public prince also makes his presence known. One day the older prince asks him and Myla two things. One, to not participate in the war, and two, to help him and his younger brother get out of the castle.",
    "Game of Maths": "Once upon a time, five aristocratic families in the mythical land of Mathsteros meanwhil full creatures mathematicals forgot reappear and the five families fight for the Mathsthrone so which family will win the Mathsthrone and what will happen tomathematical creatures ?",
    "Pi": "When a group of students attack a math teacher they did not expect reprisals...",
    "The end is Near": "During the Cold War in 1990, the URSS opposed the USA.<br>Alba is a 24 year old young woman, from Florida in the USA. She wanted to be a great mathematician, so she worked very hard in her studies.<br>Lev is a 25 year old Russia soldier, serving the URSS. They meet in Germany and fall in love each other.<br>One day, they find on the floor a coded message and they decode it : \"The end is near\". They must stop this war, therefore they have infiltrated each other’s country.<br>They discover a nuclear bomb with a 5 min countdown, they try to undo it as quickly as possible thanks to math formulas, they finally survived.<br>Five years later, they finally decided to get married in France, Alba becomes a mathematician, and was recognized for her feat with Lev, her dream had become real.",
    "The Impossible Love Equation": "In a world where everyone born with an equation and where, to have the right to be together, both people must have the same equation, Jason and Alyssa try to live their love story despite this rule. Can this love story be the most beautiful story of their life ?",
    "Math Lovers": "The story is about a girl who is not smart in math. She is in difficulty and her teacher decided to organize tutoring sessions with a certain Oliver. Also, Lara is in last year of high school and she's never kissed a boy, so her best friend Joe made a deal with her. Except it didn't go as planned...",
    "The Beauty and the Beast (revisited version)": "The beginning is like the movie, but when she arrives at the castle, she falls in the mirror and she finds herself in a other world. She sees a lot of pictures, these are the memories of the Beast. She decides to enter the picture. In every picture there is an enigma of maths. Like decoding, coding, resolution of equations, problems, write some programms. To find the solution, she has to use her logic... She must enter in all pictures, to save the Beast.",
    "Love or Math": "At his first party, Matt, a teenager gifted in mathematics did not expect to meet the one who could be the woman of his life. But mathematics took a very big place in their relationship, so Matt had to make a choice. Love or Math ?",
    "Dark Hole": "A lot of natural disasters is threatening the Earth. These ones are caused by a supermassiv black hole located so far from the planet. For example, People had to face with tsunami, earth quakes, hurricanes... One of the main characters, Marie Curry, a french mathematician, solve a hard equation to join the black hole with a starship able to go across a glass hole. Only three people can save the Earth : Marie Curry, John Burton and Steve Mcqueen. The team are going to live many dangerous adventures and issues throughout the universe. Will they be able to save humanity and come back alive ?",
    "Equation's World": "This story takes place on a planet where all the people of each territory has its own geometric shape on their head, wich is representing where they are from. Four kind of geometric shapes are on this planet. First, the circle, second, the triangle, and third, the square. But there was a fourth population was living in a beautiful place with a high technology, hidden from the others. They were the Heart. One day the other territory discovered this peauceful land...",
    "Divergeant": "This story takes place in a world divided into three social classes according to IQ and distinct logical-mathematical, artistic and manual abilities, led by the dictator Edgard. There is the first class with an IQ of more than 128. They are destined to exercise professions in the scientific field. They are called intellectuals. The 2nd class is with an IQ of more than 127 to 112 who are in the field of Arts and finally the last category, the one with an IQ of less than 112. This social class is intended to do jobs like hairdresser, housekeeper, worker, etc. Nathan, a young 16-year-old boy belonging to the lowest social class, turns out to be a genius in maths and physics. He is divergeant. In the greatest of secrets, he rejoined a movement of divergeants. Toogether, they will try to overthrow the government in order to realize their dream...",
    "The Ghost": "The story begins in a prison, with a man that seems crazy. Inside his prison cell we see many and many math equations. The guardian never look in his cell because he is in this prison till his fifteen for an unknown crime that is classified as national secret. The guardian gives him his food one time per day. One day the guardian see that the last food that he gives to him is still untouched so he looks in the cell and doesn’t see the man in. Instantly the guard triggs the alarm and an investigation began no one understand the equation on the wall. Scientists come in his cell and understand that he found a way to change dimension but before leaving he destroys a part of his work so the scientists can’t understand too.",
    "The Mathemators": "In a world where all people have super powers, four friends don't have powers but this will change...",
    "Squid Maths": "Here will be the Synopsis of the movie you clicked on. (otherwise, it's kinda bad... that sucks damn)", //no synopsis here, rude.
    "Ka To Sukeban": "Kaito is a teenager who steal some valuable ojects during the night. One friend of his father, named \"The Jocker\", a fearsome thief, offered Kaito to work with him to steal a valuable diamond. But after this burglary, Kaito is caught and emprisoned...",
    "5 less 1": "Five famous people are kidnapped. If they want escape they have to play the game called “Win or Die”. The aim of the game? Passing five steps based on mathematics and try to don’t die",
    "Puzzle": "Ilan and Chloé are specialists in treasure hunts. For a long time, they dreamed of participating in the ultimate game, the one of which we only know the name: MathsParanoia. When the day comes, they receive rule number 1: Whatever happens, nothing you are going to experience is reality. This is a game. Followed, a little later, by rule number 2: Mathematics has rules but no goal. Then rule number 3: One of you is going to die. And when the players find a first corpse, game and reality begin to merge. MathsParanoia can then really begin...",
    "One of us is lying": "The first day of school, five teenagers are in detention and one among them is diying, so the others teens are suspected of his death. After that an anonymous person is going to send them some strange messages and blackmail them",
    "The Math Solver": " It's a detective series where the man who solves the crimes is a genius in mathematics and in each crime that the secret organization of mathematics sows, he finds a mathematical problem which help him to solve the mystery to discover the assassin in each episode so that at the end of the season he solves the final mathematical enigma to defeat the boss called Mr Mathematics. The detective's name is Michael.",
    "The Class": "Today I'm going to tell you the story of the best class in North Korea. The class A ! It's a very special class because it has to try to kill their math teacher because it's a very dangerous monster. Their teacher gave them 1 year to try to kill him, everything is allowed, the only rules to respect is that to try to kill him you must have at least 15/20 in the math test. The state, which is aware of the situation, decides to trust the best class in the country. The students will work a lot and assiduously revise their math course to try to have more than 15 at all their tests. Even if the students manage to have the expected results, no one can kill the math teacher. At the end of the year all the students have accomplish to have a minimum of 15/20 in their evaluation. So they decided to do it right and prepared a plan. Once the plan was established, they took action and accomplish to kill their math teacher by stabbing him three times in very strategic places. To thank them, the government offered them a position in the most reputable company in Korea with a nice check.",
    "Espace Maths": "During night Marry is kidnapped and is caught with six persons. She will gather all her own self-control, bravery and understanding in maths to survive. Her destiny and the destiny of the city depends on her !",
    "The Hacker's Game": "Four friends, Luna, Lindsay, Gabi and Owen go to Chicago to participate in a national Maths competition organized every year in all the United States. They are going to stay with their friend Cassiel, a young mathematician gamer millionaire. But when they arrive at his house, he comes across his servant, Charles. This reveals to them that Cassiel has disappeared, kidnapped by the half-brother of Cassiel, a hacker, that calls himself \"terminator\". The game is simple: the group of friends must resolve each problem given by Terminator in order to find a password. But with each failure, Cassiel will suffer torture.They alone are able, thanks to their incredible talent for math, to save Cassiel. But they must act quickly, because time is running out before the worst happens...",
    "The detectives": "The four high school students will solve murders while trying to concentrate on their studies. Will they be able to complete their studies ?",
    "How to get away with operations": "Students in a criminology class have to solve some cases using law... and their math skills !",
    "The Test": "Ruined and ready for anything, Joe agrees to participate in a mysterious game. A huge sum of money is promised to the winner but he does not know that the losers will never be found."
  },
  "French": {
    "selection": "SÉLECTIONNEZ VOTRE SÉRIE/FILM<br>DANS LA ",
    "presentation": "Le film / la série est :",
    "Revenge of Math": "Après avoir reçu des menaces de mort de son ancien rival et détruit tout ce qu'il possède, la seule arme de notre héros pour se venger, ce sont les mathématiques, qui lui donnent une force physique et mentale impressionnante.",
    "Math Hard": "Lors d'une fête, le Nakatomi Plaza est attaqué par trois terroristes nommés Math, Emma et Tic, qui sont d'ailleurs des génies des mathématiques. Ils vont cacher trois bombes dans le bâtiment. Pour désamorcer la première, vous devez résoudre la conjecture de Poincaré. Pour la deuxième, vous devez déchiffrer un code. Et pour la dernière, vous devez casser un programme. Cependant, la seule personne qui peut sauver tout le monde, John MathClain, ne connaît rien aux mathématiques, car il aime la philosophie, les arts et l'histoire. Pourra-t-il sauver tous les otages ?",
    "Breaking Maths": "C'est l'histoire d'un professeur de mathématiques qui a trouvé un moyen de gagner de l'argent, mais il ne sait pas que cette vie changera sa vie pour toujours...",
    "Father's Plan": "So Father's plan est un film dans lequel un adolescent veut devenir boxeur professionnel mais il est très mauvais en maths, son père lui dit d'améliorer ses compétences en maths car cela l'aidera dans le mma. Pendant le film, l'adolescent va comprendre le conseil de son père.",   
    "New Life": "Bryan est un homme qui a vécu dans la pauvreté depuis son enfance avec des parents qui avaient peu de revenus, cependant c'est un homme qui aime les mathématiques, son talent lui permettra de participer et de gagner un concours qui contient une grande somme d'argent en plus d'obtenir un emploi stable pour travailler dans la recherche scientifique. Après la victoire de sa vie, Bryan partage cet argent avec sa famille.",
    "Mathematician's World": "Après avoir été malmené pendant deux ans, Albert Mathstein décide de mettre fin à ses jours, mais Dieu lui donne une seconde chance dans un autre monde..",
    "The Luckiest": "Après avoir rencontré le professeur Brown, Martin, un jeune homme endetté, décide de créer avec lui une théorie tordue pour gagner beaucoup d'argent et pouvoir rembourser son prêt. Mais le chef de gang el sombrero, son prêteur, tente de découvrir sa théorie et de lui voler son argent. Martin parviendra-t-il à cacher sa théorie et à garder son argent ?",
    "JumanPI": "C'est l'histoire de quatre adolescents, Jake, Swan, Clara et Mike, qui sont emprisonnés dans un jeu vidéo appelé JUMANPI. Pour en sortir, ils doivent passer des tests mathématiques et physiques. Les épreuves seront difficiles et dangereuses.",
    "Koh Sinus": "Dans cette série de sept épisodes, nous suivons l'histoire de sept personnes perdues sur une île. Pour quitter l'île, ils doivent résoudre des énigmes mathématiques et tenter de survivre. Chaque épisode est vu du point de vue d'un personnage. Cette série, aussi intrigante qu'amusante, est faite pour rire et se détendre. Chaque personnage a une personnalité différente, ce qui rend cette série amusante et originale. Bon visionnage...",
    "Mathman": "Un professeur de mathématiques, piqué par un compas, acquiert des superpouvoirs qui lui permettent de lancer des outils mathématiques. Il rencontrera des adversaires comme Histoman qui peut créer un globe terrestre géant. Histoman est l'antagoniste le plus détesté. Ses alliés sont ELS et le professeur de physique.",
    "The World of Math": "C'est l'histoire d'un jeune garçon qui entreprend un voyage pour retrouver sa mère à l'occasion de son anniversaire...",
    "Find by the Maths": "L'histoire commence à New York, dans un quartier riche appelé Upper East Side. Les deux personnages principaux sont Stondy et Michael. Tous deux sont dans une école privée très expansive et si Michael est là, c'est grâce à une bourse d'études en mathématiques. Alors que Stondy est riche, Michael, contrairement aux autres élèves, vit dans un quartier classique de Brooklynn. Il vit avec ses parents et ses frères. Comme ses camarades de classe n'acceptent pas sa différence, Michael est bien seul. Pour changer cela, il décide de mettre au point une astuce pour obtenir toutes les réponses de tous les examens. Il commence à être apprécié par ses camarades de classe, mais des problèmes apparaissent rapidement....",
    "Disappearance": "Afin de retrouver leur ami et autre disparu, cinq amis d'enfance doivent réaliser une équation mathématique avec laquelle ils pourront reconstituer une carte, sur laquelle figurera la position des personnes disparues. Eliotte, Benjamin, Clarisse, Lana, Ella partent à l'aventure pour retrouver leur ami et les personnes disparues. Pour cela, ils devront être dotés d'intelligence pour résoudre les équations qui les attendent.",
    "Stranger Maths": "Un professeur de mathématiques veut avoir un super pouvoir. Il a donc utilisé une calculatrice artefact dans ses cours, ce qui lui a permis d'avoir un super pouvoir et d'attirer l'attention des élèves. Par exemple, dans le deuxième épisode, si un gars fait naître un groupe de grenouilles dans le premier nombre, c'est un mauvais événement. Le troisième épisode est un autre gars qui peut se transformer en mouche s'il voit une fractale et qu'il veut créer une WW3. Dans l'épisode 4, une fille peut créer un outil mathématique pour que les hommes veuillent la kidnapper. Ensuite, une fille peut se transformer en probabilité et veut donner de l'argent aux sans-abri. A la fin de l'épisode, il y a une bataille entre l'élève et le professeur. Les étudiants gagnent, mais le professeur n'est pas vraiment mort...<br><br><u>La traduction est mauvaise car le texte est flingué d'erreurs, mes plus sincères excuses<u>",
    "Shrek (revisited version)": "Donc pour ce film de Shrek, ce sera la même histoire que le film original mais avec quelque chose de nouveau comme des blagues et nous n'allons pas faire les quatrièmes films de la saga. Nous ne faisons que le premier film parce que nous n'avons pas assez de temps pour faire les quatre films.",
    "Ridiculous Maths": "Faire une satire de la politique française en faisant des débats mathématiques.",
    "My friend this genius": "Steve, un agent secret du FBI, recherche depuis plusieurs mois les plus gros trafiquants de drogue du Texas. Pour ce faire, il doit à chaque fois résoudre de véritables énigmes pour trouver la moindre piste. Un jour, il prend la défense de Tobias, un garçon de 15 ans qui s'avère être un as des maths et une énigme, harcelé par les garçons de son quartier. Mais, par inadvertance, Steve laisse tomber son taser et Tobias part à sa recherche pour le lui rendre et le remercier. Mais il découvre sa base et ses secrets. Tobias propose son aide à Steve. Au début, celui-ci refuse et veut effacer le souvenir, mais accepte car il est désespéré. C'est le début d'une longue amitié...",
    "Maleficient calculators": "L'histoire se passe en 2069 et les calculatrices ont presque conquis le monde. Le protagoniste est Texas, un garçon originaire du Texas. Avec un groupe de scientifiques, il va essayer d'arrêter le patron des calculatrices, Géant Casio, en résolvant son équation pour le tuer. Mais il y a un prix : celui qui découvrira la solution et la communiquera à G.C. devra mourir avec lui. Texas trouvera-t-il l'équation et acceptera-t-il de mourir pour sauver le monde ?",
    "Hope to see you again...": "Pendant la Seconde Guerre mondiale, Emile Moreau, un jeune juif docteur en mathématiques, rencontre une petite fille abandonnée nommée Valentina. Ils vivaient dans une ville sans histoire et sans problème. Il décide de l'accueillir chez lui et de lui enseigner tout ce qu'il sait en matière de mathématiques. Un jour, au travail, l'alarme de guerre retentit dans toute la ville. Emile se précipite chez lui mais ne trouve personne. En tant que juif, il est emmené dans un camp. Emile survivra-t-il ? Où est Valentina ? Se reverront-ils ?",
    "The Mental Calculus": "La dame décide d'affronter dans un duel mathématique tous les hommes de sa ville, elle rencontrera plusieurs difficultés mais ne se fatiguera jamais les bras, pour prouver que les femmes ne sont pas inférieures et qu'elles peuvent même être plus intelligentes. Poly Gon réussira son objectif et changera les esprits.",
    "Strategic War": "Dans un monde de magie, la paix peut être difficile à obtenir. Dans ce monde, tous les royaumes entrent en guerre les uns contre les autres. Pour le Royaume de Flos Viridis, il ne reste qu'un seul espoir, Koji, un mathématicien, qui travaille actuellement comme orthoprothésiste et qui est le meilleur stratège de ce royaume. Il refuse, mais lorsque le roi demande à son meilleur ami, Myla, un soldat de renom, de faire partie de la garde royale, il accepte. Vivant désormais au château pour aider le roi, il remarque que le prince, le fils du roi, n'a peut-être jamais mis les pieds hors du château et il n'est pas le seul puisqu'un prince plus jeune, inconnu du public, fait également parler de lui. Un jour, le prince plus âgé lui demande, ainsi qu'à Myla, deux choses. D'une part, de ne pas participer à la guerre et, d'autre part, de les aider, lui et son jeune frère, à sortir du château.",
    "Game of Maths": "Il était une fois cinq familles aristocratiques dans le pays mythique de Mathsteros où les créatures mathématiques oubliées réapparaissent et les cinq familles se battent pour le Mathsthrone. Quelle famille gagnera le Mathsthrone et qu'arrivera-t-il aux créatures mathématiques ?",
    "Pi": "Lorsqu'un groupe d'élèves attaque un professeur de mathématiques, ils ne s'attendent pas à des représailles...",
    "The end is Near": "En 1990, pendant la guerre froide, l'URSS s'oppose aux États-Unis.<br>Alba est une jeune femme de 24 ans, originaire de Floride, aux États-Unis. Elle veut devenir une grande mathématicienne et travaille très dur dans ses études.<br>Lev est un soldat russe de 25 ans, au service de l'URSS. Ils se rencontrent en Allemagne et tombent amoureux l'un de l'autre.<br>Un jour, ils trouvent sur le sol un message codé qu'ils décodent : \"La fin est proche\". Ils doivent arrêter cette guerre, c'est pourquoi ils se sont infiltrés dans le pays de l'autre.<br>Ils découvrent une bombe nucléaire avec un compte à rebours de 5 minutes, ils essaient de la désamorcer le plus rapidement possible grâce à des formules mathématiques, ils ont finalement survécu.<br>Cinq ans plus tard, ils décident enfin de se marier en France, Alba devient mathématicienne, et est reconnue pour son exploit avec Lev, son rêve est devenu réalité.",
    "The Impossible Love Equation": "Dans un monde où chacun naît avec une équation et où, pour avoir le droit d'être ensemble, les deux personnes doivent avoir la même équation, Jason et Alyssa tentent de vivre leur histoire d'amour en dépit de cette règle. Cette histoire d'amour peut-elle être la plus belle histoire de leur vie ?",
    "Math Lovers": "L'histoire est celle d'une jeune fille qui n'est pas très douée en mathématiques. Elle est en difficulté et son professeur a décidé d'organiser des séances de tutorat avec un certain Oliver. De plus, Lara est en dernière année de lycée et elle n'a jamais embrassé un garçon, alors son meilleur ami Joe a passé un accord avec elle. Mais cela ne s'est pas passé comme prévu....",
    "The Beauty and the Beast (revisited version)": "Le début est comme dans le film, mais quand elle arrive au château, elle tombe dans le miroir et se retrouve dans un autre monde. Elle voit beaucoup d'images, ce sont les souvenirs de la Bête. Elle décide d'entrer dans le tableau. Dans chaque image, il y a une énigme mathématique. Comme le décodage, le codage, la résolution d'équations, de problèmes, l'écriture de programmes. Pour trouver la solution, elle doit utiliser sa logique... Elle doit entrer dans toutes les images, pour sauver la Bête.",
    "Love or Math": "Lors de sa première fête, Matt, un adolescent doué pour les mathématiques, ne s'attendait pas à rencontrer celle qui pourrait être la femme de sa vie. Mais les mathématiques ont pris une place très importante dans leur relation, et Matt a dû faire un choix. Amour ou Mathématiques ?",
    "Dark Hole": "De nombreuses catastrophes naturelles menacent la Terre. Celles-ci sont causées par un trou noir supermassif situé très loin de la planète. Par exemple, les gens ont dû faire face à des tsunamis, des tremblements de terre, des ouragans... L'un des personnages principaux, Marie Curry, une mathématicienne française, résout une équation difficile pour rejoindre le trou noir à l'aide d'un vaisseau capable de traverser un trou de verre. Seules trois personnes peuvent sauver la Terre : Marie Curry, John Burton et Steve Mcqueen. L'équipe va vivre de nombreuses aventures et problèmes dangereux à travers l'univers. Parviendront-ils à sauver l'humanité et à revenir vivants ?",
    "Equation's World": "L'histoire se déroule sur une planète où tous les habitants de chaque territoire ont une forme géométrique sur la tête, qui représente leur lieu d'origine. Il existe quatre types de formes géométriques sur cette planète. La première est le cercle, la deuxième le triangle et la troisième le carré. Mais il y avait une quatrième population qui vivait dans un endroit magnifique avec une technologie de pointe, cachée des autres. C'était le Cœur. Un jour, les autres territoires ont découvert cette terre poissonneuse...",
    "Divergeant": "L'histoire se déroule dans un monde divisé en trois classes sociales selon le QI et les capacités logico-mathématiques, artistiques et manuelles distinctes, dirigé par le dictateur Edgard. Il y a la première classe dont le QI est supérieur à 128. Ils sont destinés à exercer des professions dans le domaine scientifique. On les appelle les intellectuels. La 2ème classe est avec un QI de plus de 127 à 112 qui sont dans le domaine des Arts et enfin la dernière catégorie, celle avec un QI de moins de 112. Cette classe sociale est destinée à exercer des métiers tels que coiffeur, femme de ménage, ouvrier, etc. Nathan, un jeune garçon de 16 ans appartenant à la classe sociale la plus basse, se révèle être un génie en mathématiques et en physique. Il est divergent. Dans le plus grand des secrets, il a rejoint un mouvement de divergents. Ensemble, ils vont tenter de renverser le gouvernement pour réaliser leur rêve...",
    "The Ghost": "L'histoire commence dans une prison, avec un homme qui semble fou. Dans sa cellule, on voit de nombreuses équations mathématiques. Le gardien ne regarde jamais dans sa cellule car il est dans cette prison jusqu'à ses quinze ans pour un crime inconnu qui est classé secret national. Le gardien lui donne à manger une fois par jour. Un jour, le gardien voit que la dernière nourriture qu'il lui a donnée n'a pas été touchée, il regarde donc dans la cellule et ne voit pas l'homme. Immédiatement, le gardien déclenche l'alarme et une enquête est ouverte. Personne ne comprend l'équation sur le mur. Des scientifiques viennent dans sa cellule et comprennent qu'il a trouvé un moyen de changer de dimension, mais avant de partir, il détruit une partie de son travail pour que les scientifiques ne puissent pas comprendre non plus.",
    "The Mathemators": "Dans un monde où tout le monde a des super-pouvoirs, quatre amis n'en ont pas, mais cela va changer...",
    "Squid Maths": "Here will be the Synopsis of the movie you clicked on. (otherwise, it's kinda bad... that sucks damn)", //no synopsis here, rude.
    "Ka To Sukeban": "Kaito est un adolescent qui vole des objets de valeur pendant la nuit. Un ami de son père, nommé \"Le Jocker\", un redoutable voleur, propose à Kaito de travailler avec lui pour voler un diamant de grande valeur. Mais après ce cambriolage, Kaito est attrapé et emprisonné...",
    "5 less 1": "Cinq personnes célèbres sont kidnappées. Pour s'échapper, elles doivent jouer au jeu “Gagner ou mourir“. Le but du jeu ? Passer cinq étapes basées sur les mathématiques et essayer de ne pas mourir.",
    "Puzzle": "Ilan et Chloé sont des spécialistes des chasses au trésor. Depuis longtemps, ils rêvent de participer au jeu ultime, celui dont on ne connaît que le nom : MathsParanoia. Le jour venu, ils reçoivent la règle numéro 1 : Quoi qu'il arrive, rien de ce que vous allez vivre n'est la réalité. C'est un jeu. Suivie, un peu plus tard, de la règle numéro 2 : Les mathématiques ont des règles mais pas de but. Puis la règle numéro 3 : l'un d'entre vous va mourir. Et lorsque les joueurs trouvent un premier cadavre, le jeu et la réalité commencent à se confondre. La MathsParanoia peut alors vraiment commencer...",
    "One of us is lying": "Le jour de la rentrée scolaire, cinq adolescents sont en détention et l'un d'entre eux est mort, si bien que les autres adolescents sont soupçonnés de sa mort. Ensuite, une personne anonyme va leur envoyer des messages étranges et les faire chanter.",
    "The Math Solver": " C'est une série policière où l'homme qui résout les crimes est un génie des mathématiques et dans chaque crime que l'organisation secrète des mathématiques sème, il trouve un problème mathématique qui l'aide à résoudre le mystère pour découvrir l'assassin dans chaque épisode de sorte qu'à la fin de la saison, il résout l'énigme mathématique finale pour vaincre le patron appelé M. Mathématiques. Le détective s'appelle Michael.",
    "The Class": "Aujourd'hui, je vais vous raconter l'histoire de la meilleure classe de Corée du Nord. La classe A ! C'est une classe très spéciale car elle doit essayer de tuer son professeur de maths car c'est un monstre très dangereux. Leur professeur leur a donné 1 an pour essayer de le tuer, tout est permis, la seule règle à respecter est que pour essayer de le tuer il faut avoir au moins 15/20 au test de maths. L'état, conscient de la situation, décide de faire confiance à la meilleure classe du pays. Les élèves travailleront beaucoup et réviseront assidûment leur cours de maths pour essayer d'avoir plus de 15 à tous leurs tests. Même si les élèves parviennent à obtenir les résultats escomptés, personne ne peut tuer le professeur de mathématiques. A la fin de l'année, tous les élèves ont accompli l'exploit d'avoir un minimum de 15/20 à leur évaluation. Ils ont donc décidé de bien faire les choses et ont préparé un plan. Une fois le plan établi, ils sont passés à l'action et ont réussi à tuer leur professeur de mathématiques en le poignardant trois fois à des endroits très stratégiques. Pour les remercier, le gouvernement leur a offert un poste dans l'entreprise la plus réputée de Corée, assorti d'un joli chèque.",
    "Espace Maths": "Pendant la nuit, Marry est kidnappée et se retrouve avec six personnes. Elle devra faire appel à toute sa maîtrise de soi, à son courage et à ses connaissances en mathématiques pour survivre. Son destin et celui de la ville dépendent d'elle !",
    "The Hacker's Game": "Quatre amis, Luna, Lindsay, Gabi et Owen se rendent à Chicago pour participer à un concours national de mathématiques organisé chaque année dans tous les Etats-Unis. Ils vont loger chez leur ami Cassiel, un jeune mathématicien joueur millionnaire. Mais lorsqu'ils arrivent chez lui, il tombe sur son domestique, Charles. Celui-ci leur révèle que Cassiel a disparu, kidnappé par le demi-frère de Cassiel, un hacker, qui se fait appeler \"terminator\". Le jeu est simple : le groupe d'amis doit résoudre chaque problème donné par Terminator afin de trouver un mot de passe. Mais à chaque échec, Cassiel sera torturé... Eux seuls sont capables, grâce à leur incroyable talent pour les mathématiques, de sauver Cassiel. Mais ils doivent agir vite, car le temps presse avant que le pire n'arrive...",
    "The detectives": "Les quatre lycéens vont devoir résoudre des meurtres tout en essayant de se concentrer sur leurs études. Parviendront-ils à terminer leurs études ?",
    "How to get away with operations": "Les étudiants d'un cours de criminologie doivent résoudre des cas en s'appuyant sur la loi... et sur leurs compétences en mathématiques !",
    "The Test": "Ruiné et prêt à tout, Joe accepte de participer à un jeu mystérieux. Une énorme somme d'argent est promise au gagnant mais il ignore que les perdants ne seront jamais retrouvés."
  }
}

buttons.forEach(function(button) {
  button.onclick = function() {
    content = button.textContent;
    synopsis.innerHTML = `<span class="movie">${lang[language.textContent]["presentation"]} <span class="titleMovie">${content}</span></span> <br><br><br><br>${lang[language.textContent][content]}`
    modal.style.display = "block";
  };
});

closeBtn.onclick = function() {
  modal.style.display = "none";
};

window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
};

toggle.addEventListener('change', function() {
  if(this.checked) {
    language.textContent = 'French';
    title.innerHTML = `${lang["French"]["selection"]} CATÉGORIE "${document.title.replace("Mathflix | ", "").toUpperCase()}"`;
  } else {
    language.textContent = 'English';
    title.innerHTML = `${lang["English"]["selection"]} ${document.title.replace("Mathflix | ", "").toUpperCase()} CATEGORY`;
  };
});